services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - VAPI_SECRET_KEY=${VAPI_SECRET_KEY}
      - VAPI_API_KEY=${VAPI_API_KEY}
      - PUBLIC_BACKEND_URL=${PUBLIC_BACKEND_URL}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID:-}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN:-}
      - ENVIRONMENT=development
    volumes:
      - ./src:/app/src
      - ./vapi:/app/vapi
      - ./scripts:/app/scripts
    command:
      [
        "uvicorn",
        "src.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
      ]
    restart: unless-stopped
